apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  labels:
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: es
    port: 9200
    protocol: TCP
